### ISSUE TITLE
Request for Assistance

### ISSUE THREAD

**Issue by electron1963** [gwww/elkm1#48]
First - thanks for developing this package and posting it for others to use - much appreciated!
I have installed your elkm1 package and have been successfully using the package.
I am fairly new to python.  I am looking for some help.
I have an Elan Automation System and have the ELKM1 tied into the Elan - no issues.
I am creating a user interface to control various aspects of the ELM panel - using buttons on the interface to runs tasks on the ELK.
That is running fine as well.  I have a requirement to interact with the ELK panel and think your package will do the trick.
I am passing data to a python server from the Elan.  The data is plaintext and is a numeric string.  I would like to have your ELK script running in interact mode and pass data from my python server to the output window of the ELK script.  
I appreciate that this is not a issue with your script, but would very much appreciate any direction you could pass along on how to achieve this.

**Comment by gwww** [comment]
I can try and help. I'm not sure what you mean by "output window of the Elk Script". Maybe describe what in terms of what you would like to have happen to the Elk with this data that is coming from the Elan.

**Comment by electron1963** [comment]
Thanks for getting back to me! 

I refering to the interactive screen - command line. See picture. 


So, here is what I tring to do. In my Elan Automation, I will have a control screen with multiple buttons. Those buttons with send to ELK the command like - 09tn01100C3, which runs task 12. I send this via TCP through the driver in the Elan Automation. That works fine - no issue, the task runs. 
Now, I want to control access to this screen, so I have a authentication screen which displayed first. That authentication screen is simply a keypad which is constructed inside the Elan Automation. When a keypad button is pressed the pressed button sends a 1 or 2 or 3 or ..... to a seperate device (raspberry pi) which is running a python server. That server has rules and conditions to ensure the code is a 4 digit code ....., but the end result is a 4 digit code represented as a string. I want to send that code to ELK from this seperate server using the "Request Valid User Code Areas" command. The return will get parsed to determine If that code entered is a valid user code of any area. If the code is valid then that will trip an output. That output will serve as a trigger to the Elan Automation that the code is valid and to proceed to the control screen. 
I do not have communication from the python server to the ELK. Communication is only through the Elan Automation. So the way I see it, either I pass data from the python server to your command line, which will send it to the ELK or I somehow embed my keypad script inside your script. 
I haven't got it all figured out, but the if I think if I could communicate with the command line of the interactive elk script, that would do a long way in helping to move this along. 

Again, I appreciate that none of this is your problem - everything you have written works perfectly. I am just looking for a way to interact with you command line. 

Thanks again for even getting back to me - so may people don't - so Thank You! If I don't hear back from you, I understand.

**Comment by gwww** [comment]
I add this to the repo which should help: https://github.com/gwww/elkm1/blob/main/examples/simple_program.py

NOTE: you need the latest lib which is version 1.2.1 (or higher) for the program to work.

**Comment by electron1963** [comment]
Thanks!!!!! 

Subsituted a valid Code and ran the simple_program.py, it runs returns: 
{'user_code': 0, 'valid_areas': 0, 'diagnostic': '3030F04E', 'user_code_length': 4, 'user_code_type': 1, 'temperature_units': 'C'}, and then terminates. 

The code I used is a valid code for Area 7,8. 
if I run the command 0Cua001063002D from Elan it returns 19UA001063C13130F64D41C009F, indicating 1063 is valid in area 1,2,7,8. 

Moreover, although I very much appreciate you taking the time to do this - could I ask for a brief explaination? 

Again, Thank You very much.

**Comment by gwww** [comment]
Did you get the 1.2.1 version of the lib?

**Comment by gwww** [comment]
Here's what I get with an invalid code:
```
got_data '19UA001234003132300541C00DD'
{'user_code': 1234, 'valid_areas': 0, 'diagnostic': '31323005', 'user_code_length': 4, 'user_code_type': 1, 'temperature_units': 'C'}
```

And with a valid code (X's over my code):
```
got_data '19UA00XXXXFF3838320242C009A'
{'user_code': XXXX, 'valid_areas': 255, 'diagnostic': '38383202', 'user_code_length': 4, 'user_code_type': 2, 'temperature_units': 'C'}
```
Something must be different in your setup.

I'll add some comments to the example and push that to help with the explanation.

This project did uncover a bug in the lib, which is fixed in 1.2.1 -- so yeah and thanks!

**Comment by electron1963** [comment]
I thought I did upgrade. 
Reran the install - now is 1.2.1 
now get a valid code! 

will look at your comments in the code. 


THANK YOU VERY MUCH!!!!!!

**Comment by electron1963** [comment]
Hi Glenn 

Sorry to trouble you again, but there seems to be an issue still. 
I incorpororated my keypad input into the simple_program.py you posted. 
I am getting a string code but that code is not passed to message.py properly. 
I modified ua_encode() in the message.py with a print statement 
print(user_code) 
It seems to hit this statement twice. The first time the value is 0. The second time the value has the user code. 
I have modified some of the log printouts to identify where thing are coming from - so don't be alarmed. 
Here is the output: 

Synchronizing panel..... 
ua_encode - User Code = 0 
write_data '0Cua0000000037' 
got_data '17IC00000000000000001007B' 
got_data '19UA000000003030F04E41C00C3' 
Sync complete!!!? 
ua_encode - User Code = 1063 
Invalid message '19UA000000003030F04E41C00C3' 
Traceback (most recent call last): 
File "/home/pi/.local/lib/python3.9/site-packages/elkm1_lib/message.py", line 67, in decode 
self.call_handlers(cmd, decoder(msg)) 
File "/home/pi/.local/lib/python3.9/site-packages/elkm1_lib/message.py", line 55, in call_handlers 
handler(**decoded_msg) 
File "/home/pi/.local/lib/python3.9/site-packages/elkm1_lib/elk.py", line 56, in _sync_complete 
self._message_decode.call_handlers("sync_complete", {}) 
File "/home/pi/.local/lib/python3.9/site-packages/elkm1_lib/message.py", line 55, in call_handlers 
handler(**decoded_msg) 
File "/home/pi/.local/lib/python3.9/site-packages/bin/elk_input2.py", line 39, in sync_complete 
self.elk.send(ua_encode(self.user_code)) 
File "/home/pi/.local/lib/python3.9/site-packages/elkm1_lib/message.py", line 525, in ua_encode 
return MessageEncode(f"0Cua{user_code:06}00", "UA") 
ValueError: '=' alignment not allowed in string format specifier 

The above exception was the direct cause of the following exception: 


Any ideas? 

Thanks again Glenn! 

Regards, 
Kevin

**Comment by electron1963** [comment]
Hi Glenn 

Yes, me again. 
Thanks for the info on us_encode - have that working perfectly! 

I have one last issue that I have to tackle. When a code is verified as valid or invalid, I am wanting to trip and output. 
If the code is valid I want to trip output 32 ( Elk output 31 ) 
if the code is invalid I want to trip output 16 ( Elk output 15 ) 

I added the code to parse out the valid zone and then code to check if that code is valid for the area in question - no issues. 
I added a handler for ct_encode and there I run into an issue - AttributeError: 'Elk' object has no attribute 'ct_encode. 
My code with the Output added: 

class MyApp: 
17 def __init__(self, url, user_code, output): 
18 # Setting element list to empty list means no elements are synced on> 
19 # i.e.: saves startup sync time if you don't need it! 
20 self.elk = Elk({"url": url, "element_list": []}) 
21 self.elk.add_handler("disconnected", self.disconnected) 
22 self.elk.add_handler("connected", self.connected) 
23 self.elk.add_handler("sync_complete", self.sync_complete) 
24 self.elk.connect() 
25 
26 self.user_code = user_code 
27 self.output = output 
28 
29 self.elk.run() 
30 
31 def disconnected(self): 
32 print("Disconnected!!!") 
33 self.elk = None 
34 exit(0) 
35 
36 def connected(self): 
37 print("Connected!!!") 
38 
39 def sync_complete(self): 
40 print("Sync complete!!!") 
41 self.elk.add_handler("UA", self.ua_response) 
42 self.elk.send(ua_encode(self.user_code)) 
43 self.elk.add_handler("CT", self.ct_response) 
44 self.elk.send(ct_encode(self.output)) 
45 
46 def ct_response(self): 
47 print('Output in elk_input = ',output) 
48 self.elk.disconnect() 
50 def ua_response(self, **kwargs): 
51 response = str(kwargs) 
52 matches = re.search(regex, response, re.MULTILINE) 
53 if matches: 
54 print ("Match was found at {start}-{end}: {match}".format(start > 
55 
56 for groupNum in range(0, len(matches.groups())): 
57 groupNum = groupNum + 1 
58 
59 print ("Group {groupNum} found at {start}-{end}: {group}".fo> 
60 print(matches.group(1)) 
61 if (int(matches.group(1))) & (1 << 7): 
62 print('Valid') 
63 self.elk.ct_encode(31) 
64 time.sleep(5) 
65 self.elk.ct_encode(31) 
66 self.elk.disconnect() 
67 else: 
68 print('Invalid') 
69 self.elk.ct_encode(15) 
70 time.sleep(5) 
71 self.elk.ct_encode(15) 
72 self.elk.disconnect() 

Do you mind??? Promise, last time I will bug you!!

**Comment by gwww** [comment]
Two quick tips. Posting code is more readable when its formatted using the triple backticks. Second tip, is to see what's possible take a look at any method labelled "Helper". In this case, if I understand correctly, you're looking for an "Output" helper (https://github.com/gwww/elkm1/blob/main/elkm1_lib/outputs.py).

I think you want something like this:
```
    def ua_response(self, **kwargs):
        """Got a response to our UA message!"""
        if kwargs["user_code"] == the_code_i_think_is_valid:
           self.elk.outputs[the_output_number_i_want_to_turn_on, time_in_seconds_to_turn_on].turn_on()
```
If you want to check which areas, you'll have to do a bit more work. They are in "raw" form and accessed through `kwargs["areas"]`. To see what any message decodes as take a look at the code in `message.py`. For example, for the UA message this: https://github.com/gwww/elkm1/blob/main/elkm1_lib/message.py#L269-L274

As you've already noted, the library uses base 0 numbering for elements, whereas the actual ElkM1 uses base 1 to refer to elements. So to affect output 5 on the Elk, pass 4 as the argument to `turn_on`.

**Comment by electron1963** [comment]
if i insert 

self.elk.outputs[31,5].turn.on() 

in the ua_response, I get 

AttributeError: 'Elk' object has no attribute 'outputs' 

Don't understand. 

Do I need a handler? Some other code somewhere else? 

Sorry to be so needy, If you could explain this I understand and would bug you any more 

Thanks Glenn

**Comment by gwww** [comment]
Change the line in `__init__` where `self.elk` is initialized to `self.elk = Elk({"url": url, "element_list": ["outputs"]})
`

I forgot we turned off sync, which create a quicker startup, but does not give access to the element on the panel.

**Comment by electron1963** [comment]
Hi Glenn 

How about straight arm/disarm of partition 6. I see the arm helper, but don't understand how to past the area. 
Also, I thing there a bug in the user code input - if I use a code starting in a 0 - the 0 is dropped - because the code is handled as a integer? 
Could you help me out with arming - don't understand. 

Thanks again for all you previous assistence - really appreciate it! 

Kevin

**Comment by gwww** [comment]
Something like this should work (I did not try it):
```
from elkm1_lib.const import ArmLevel

elk = Elk( <your config> )
elk.connect()
elk.areas[0].arm(ArmLevel.ARM_AWAY, 1234)
```
The integer code is formatted as a 6 byte string front padded with zeros.

**Comment by electron1963** [comment]
Hi Glenn - no luck. 
my python code: 

#!/usr/bin/python 

import logging 

from elkm1_lib import Elk 
from elkm1_lib.const import ArmLevel 

elk = Elk({'url': 'elk://192.168.100.224:2101'}) 
elk.connect() 
elk.areas[6].arm(ArmLevel.ARM_AWAY, 1234) 
elk.disconnect() 

Produces: 

Traceback (most recent call last): 
File "/home/pi/.local/lib/python3.9/site-packages/bin/elk_arm2.py", line 13, in <module> 
elk.areas[6].arm(ArmLevel.ARM_AWAY, 1234) 
File "/usr/lib/python3.9/enum.py", line 405, in __getattr__ 
raise AttributeError(name) from None 
AttributeError: ARM_AWAY

**Comment by gwww** [comment]
What version of the library are you using?

**Comment by electron1963** [comment]
Ok updated Lib - runs but does arm

**Comment by electron1963** [comment]
Have the command interpretor running as the same time - nothing sent

**Comment by gwww** [comment]
Be careful upgrading. Many breaking changes. If using 1.x series then instead of ArmLevel just use an int.

**Comment by electron1963** [comment]
Hi Glenn 

Something is wrong. 
using the command interpreter - ELK with the command: 
python elk -i 
and issue the command 
area 7 arm 1 xxxx 
results in the attached screenshot - Arm screenshot.png 
I am running elkm1-lib-2.0.0 
arming the partition and then use the command 
area 7 disarm xxxx 
that works fine! 
Running the python script shown in the screenshot - arm script.png 
runs - but does nothing! No commands send, while monitoring with command interpreter. 
Can you have a look - I sure I'm doing something wrong, but for the life of me can't put my finger on it. 

Thank you - very much appreciate you assistance. 

Regards, 
Kevin

**Comment by gwww** [comment]
I don't see any screenshots. Doesn't matter though. This line of code should arm the system:
```
self.elk.areas[area_number].elements.arm(ArmLevel.ARMED_AWAY, user_code)
```
You will need to set `area_number` and `user_code`. I'm assuming `self.elk` is properly setup.

**Comment by electron1963** [comment]
#!/usr/bin/python

import logging
from elkm1_lib import Elk
from elkm1_lib.const import ArmLevel

elk = Elk({'url': 'elk://192.168.168.224:2101'})
elk.connect()
elk.areas[7].arm(ArmLevel.ARMED_AWAY, 1234)
elk.disconnect()

The above is my script.  It runs with error, but does nothing. Nothing is sent.  Panel dosn't arm.

**Comment by electron1963** [comment]
issue resolved
